/**
 * Spring PetClinic
 * Spring PetClinic Sample Application.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package petclinic.api

import petclinic.model.RestError
import petclinic.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object FailingApi {

def apply(baseUrl: String = "http://localhost:9966/petclinic/api") = new FailingApi(baseUrl)
}

class FailingApi(baseUrl: String) {

  /**
   * Produces sample error response.
   * 
   * Expected answers:
   *   code 200 : String (Never returned.)
   *              Headers :
   *                ETag - An ID for this version of the response.
   *   code 304 :  (Not modified.)
   *              Headers :
   *                ETag - An ID for this version of the response.
   *   code 400 : RestError (Bad request.)
   */
  def failingRequest(
): Request[Either[ResponseException[String, Exception], String], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/oops")
      .contentType("application/json")
      .response(asJson[String])

}
