/**
 * Spring PetClinic
 * Spring PetClinic Sample Application.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package petclinic.api

import petclinic.model.RestError
import petclinic.model.User
import petclinic.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object UserApi {

def apply(baseUrl: String = "http://localhost:9966/petclinic/api") = new UserApi(baseUrl)
}

class UserApi(baseUrl: String) {

  /**
   * Creates a user.
   * 
   * Expected answers:
   *   code 200 : User (User created successfully.)
   *              Headers :
   *                ETag - An ID for this version of the response.
   *   code 304 :  (Not modified.)
   *              Headers :
   *                ETag - An ID for this version of the response.
   *   code 400 : RestError (Bad request.)
   *   code 404 : RestError (User not found.)
   *   code 500 : RestError (Server error.)
   * 
   * @param user The user
   */
  def addUser(user: User
): Request[Either[ResponseException[String, Exception], User], Any] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/users")
      .contentType("application/json")
      .body(user)
      .response(asJson[User])

}
