/**
 * Spring PetClinic
 * Spring PetClinic Sample Application.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package petclinic.model

import java.time.LocalDate

  /**
   * Pet
   * A pet.
   */
case class Pet(
  /* The name of the pet. */
  name: String,
  /* The date of birth of the pet. */
  birthDate: LocalDate,
  `type`: PetType,
  /* The ID of the pet. */
  id: Int,
  /* The ID of the pet's owner. */
  ownerId: Option[Int] = None,
  /* Vet visit bookings for this pet. */
  visits: Seq[Visit]
)

