/**
 * Spring PetClinic
 * Spring PetClinic Sample Application.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package petclinic.model

import java.time.LocalDate

  /**
   * Pet fields
   * Editable fields of a pet.
   */
case class PetFields(
  /* The name of the pet. */
  name: String,
  /* The date of birth of the pet. */
  birthDate: LocalDate,
  `type`: PetType
)

