/**
 * Spring PetClinic
 * Spring PetClinic Sample Application.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package petclinic.model


  /**
   * Specialty
   * Fields of specialty of vets.
   */
case class Specialty(
  /* The ID of the specialty. */
  id: Int,
  /* The name of the specialty. */
  name: String
)

