/**
 * Spring PetClinic
 * Spring PetClinic Sample Application.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package petclinic.model

import java.time.LocalDate

  /**
   * Visit
   * A booking for a vet visit.
   */
case class Visit(
  /* The date of the visit. */
  date: Option[LocalDate] = None,
  /* The description for the visit. */
  description: String,
  /* The ID of the visit. */
  id: Int,
  /* The ID of the pet. */
  petId: Option[Int] = None
)

